name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # 根据需要替换为您的主分支名称

env:
  DOCKER_NAME: PYTHON-WORKNODE # 在这里定义您的 Docker 镜像名称
  DOCKER_VERSION: v0.1  # 在这里定义版本号

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_NAME }}:${{ env.DOCKER_VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_NAME }}:latest